config/routes.rb
Rails.application.routes.draw do
  root 'offices#index', as: 'home'
  resources :offices do
    resources :tools
    resources :employees
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :office
  validates :name, presence: true
  validates :birth, presence: true
  validates :address, presence: true
end

app/models/office.rb
class Office < ApplicationRecord
  has_many :tools
  has_many :employees
  validates :country, presence: true
  validates :city, presence: true
  validates :address, presence: true
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :office
  validates :name, presence: true
  validates :quantity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def new
    @employee = Employee.new
    @office = Office.find(params[:office_id])
  end

  def create
    @office = Office.find(params[:office_id])
    @employee = @office.employees.create(employee_params)
    if(@employee.save)
      redirect_to office_path(@office)
    else
      render 'new'
    end
  end

  def show
    @employee = Employee.find(params[:office_id])
  end

  def edit
    @employee = Employee.find(params[:office_id])
  end

  def update
    @employee = Employee.find(params[:office_id])
    @office = Office.find(params[:id])
    if(@employee.update(employee_params))
      redirect_to office_path(@office)
    else
      render 'edit'
    end
  end

  def destroy
    @employee = Employee.find(params[:office_id])
    @office = Office.find(params[:id])
    @employee.destroy
    redirect_to office_path(@office)
  end

  private def employee_params
    params.require(:employee).permit(:name, :birth, :address, :phone, :job, :salary)
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController

  def index
    @offices = Office.all
  end

  def new
    @office = Office.new
  end

  def create
    @office = Office.new(office_params)
    if(@office.save)
      redirect_to @office
    else
      render 'new'
    end
  end

  def show
    @office = Office.find(params[:id])
  end

  def edit
    @office = Office.find(params[:id])
  end

  def update
    @office = Office.find(params[:id])
    if(@office.update(office_params))
      redirect_to @office
    else
      render 'edit'
    end
  end

  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    redirect_to offices_path
  end

  private def office_params
    params.require(:office).permit(:country, :city, :address)
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def new
    @tool = Tool.new
    @office = Office.find(params[:office_id])
  end

  def create
    @office = Office.find(params[:office_id])
    @tool = @office.tools.create(tool_params)
    if(@tool.save)
      redirect_to office_path(@office)
    else
      render 'new'
    end
  end

  def show
    @tool = Tool.find(params[:office_id])
  end

  def edit
    @tool = Tool.find(params[:office_id])
  end

  def update
    @tool = Tool.find(params[:office_id])
    @office = Office.find(params[:id])
    if(@tool.update(tool_params))
      redirect_to office_path(@office)
    else
      render 'edit'
    end
  end

  def destroy
    @tool = Tool.find(params[:office_id])
    @office = Office.find(params[:id])
    @tool.destroy
    redirect_to office_path(@office)
  end

  private def tool_params
    params.require(:tool).permit(:name, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/employees/edit.html.erb
<div class="container text-center">
  <br><br>
<h3>Alkalmazott adatainak szerkesztése</h3>
  <br><br>
<%= form_for :employee, url: office_employee_path(@employee), method: :patch do |employee| %>
  <% if @employee.errors.any? %>
      <p class="text-danger">A név, a születés, és a lakhely mezők kitöltése kötelező!</p>
  <% end %>
  <p>
    <%= employee.label :Név %><br>
    <%= employee.text_field(:name, {:class => 'col-sm-4'}) %>
  </p>
  <p>
    <%= employee.label :Születés %><br>
    <%= employee.text_field(:birth, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= employee.label :Lakhely %><br>
    <%= employee.text_field(:address, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= employee.label :Telefonszám %><br>
    <%= employee.text_field(:phone, {:class => 'col-sm-4'}) %>
  </p>
  <p>
    <%= employee.label :Munkája %><br>
    <%= employee.text_field(:job, {:class => 'col-sm-4'}) %>
  </p>
  <p>
    <%= employee.label :Fizetés %><br>
    <%= employee.text_field(:salary, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= employee.submit("Új adatok elfogadása", {:class => 'btn btn-default'}) %>
  </p>
<% end %>
</div>

app/views/employees/index.html.erb
<h2>Alkalmazottak listája</h2>
<li><%= link_to "Új alkalmazott felvétele", new_employee_path %></li>
<% @employees.each do |employee| %>
  <h3><%= employee.name %></h3>
  <p><%= employee.birth %>, <%= employee.address %>, <%= employee.phone %></p>
  <p><%= employee.job %>, <%= employee.salary %></p>
  <p> Office id: <%= employee.office_id %></p>
<% end %>

app/views/employees/new.html.erb
<div class="container text-center">
  <br><br>
<h3>Új alkalmazott felvétele</h3>
  <br><br>
<%= form_for([@office, @office.employees.build]) do |employee| %>
  <% if @employee.errors.any? %>
      <p class="text-danger">A név, a születés, és a lakhely mezők kitöltése kötelező!</p>
  <% end %>
  <p>
    <%= employee.label :Név %><br>
    <%= employee.text_field(:name, {:class => 'col-sm-4'}) %>
  </p>
  <p>
    <%= employee.label :Születés %><br>
    <%= employee.text_field(:birth, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= employee.label :Lakhely %><br>
    <%= employee.text_field(:address, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= employee.label :Telefonszám %><br>
    <%= employee.text_field(:phone, {:class => 'col-sm-4'}) %>
  </p>
  <p>
    <%= employee.label :Munkája %><br>
    <%= employee.text_field(:job, {:class => 'col-sm-4'}) %>
  </p>
  <p>
    <%= employee.label :Fizetés %><br>
    <%= employee.text_field(:salary, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= employee.submit("Új alkalmazott létrehozása", {:class => 'btn btn-default'}) %>
  </p>
<% end %>
</div>

app/views/employees/show.html.erb
<div class="container text-center">
  <br><br>
<h2><%= @employee.name %></h2>
  <br>
  <p>Születési dátum: <%= @employee.birth %></p>
  <p>Lakhely: <%= @employee.address %></p>
  <p>Telefonszám: <%= @employee.phone %></p>
  <p>Munkakör, munka: <%= @employee.job %></p>
  <p>Bruttó órabér: <%= @employee.salary %></p>
<%= link_to "Szerkesztés", edit_office_employee_path(@employee), :class => 'btn btn-default' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RonxaatSze</title>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'%>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" <%= link_to "Irodák", home_path %><span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active" <%= link_to "Új iroda", new_office_path %></a>
          </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/offices/edit.html.erb
<div class="container text-center">
  <br><br>
<h2>Iroda adatainak a szerkesztése</h2>
  <br><br>
<%= form_for :office, url: office_path(@office), method: :patch do |office| %>
  <% if @office.errors.any? %>
      <p class="text-danger">Kérem töltse ki az összes mezőt!</p>
  <% end %>
  <p>
    <%= office.label :Ország %><br>
    <%= office.text_field(:country, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= office.label :Város %><br>
    <%= office.text_field(:city, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= office.label :Cím %><br>
    <%= office.text_field(:address, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= office.submit("Új adatok elfogadása", {:class => 'btn btn-primary'}) %>
  </p>
<% end %>
</div>

app/views/offices/index.html.erb
<div class="container text-center">
  <br>
<h2 class="border-bottom border-dark">Az irodáink listája</h2>
<% @offices.each do |office| %>
    <div class="row">
    <span class="col-lg-12 border-bottom border-dark">
  <h3><%= office.city %>, <%= office.country %></h3>
  <p><%= office.address %></p>
  <%= link_to "Alkalmazottak, eszközök", office_path(office), :class => 'btn btn-default' %>
    </span>
    </div>
<% end %>
</div>

app/views/offices/new.html.erb
<div class="container text-center">
  <br><br>
<h2>Új iroda felvétele</h2>
  <br><br>
<%= form_for :office, url: offices_path do |office| %>
  <% if @office.errors.any? %>
      <p class="text-danger">Kérem töltse ki az összes mezőt!</p>
  <% end %>
  <p>
    <%= office.label :Ország %><br>
    <%= office.text_field(:country, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= office.label :Város %><br>
    <%= office.text_field(:city, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= office.label :Cím %><br>
    <%= office.text_field(:address, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= office.submit("Új Iroda létrehozása", {:class => 'btn btn-primary'}) %>
  </p>
<% end %>
</div>

app/views/offices/show.html.erb
<div class="container text-center">
  <br>
  <div class="row">
    <span class="col-lg-12 border-bottom border-dark">
<h2><%= @office.city %>, <%= @office.country %></h2>
<p><p><%= @office.address %></p></p>
<%= link_to "Szerkesztés", edit_office_path(@office), :class => 'btn btn-default' %><br><br>
<%= link_to "Iroda törlése", office_path(@office),
            method: :delete,
            data: {confirm: 'Biztosan törlöd?'},
            :class => 'btn btn-danger' %>
    </span>
  </div>
  <br><br>
  <div class="row">
    <span class="col-lg-12 border-bottom border-dark">
<h3>Eszközök</h3>
  <br>
  <%= link_to "Új eszköz felvétele", new_office_tool_path(@office), :class => 'btn btn-default' %>
      <br><br>
      <table class="table">
  <thead>
    <tr>
      <th scope="col">Eszköz neve</th>
      <th scope="col">Mennyiség</th>
      <th scope="col">Szerkesztés</th>
      <th scope="col">Törlés</th>
    </tr>
  </thead>
  <tbody>
  <% @office.tools.each do |tool| %>
    <tr>
      <td><%= tool.name %></td>
      <td><%= tool.quantity %></td>
      <td><%= link_to "Szerkesztés", office_tool_path(tool), :class => 'btn btn-default' %></td>
      <td><%= link_to "Törlés", office_tool_path(tool),
                      method: :delete,
                      data: {confirm: 'Biztosan törlöd?'},
                      :class => 'text-danger' %></td>
    </tr>
<% end %>
  </tbody>
</table>
      </span>
  </div>

  <br><br>
  <div class="row">
    <span class="col-lg-12 border-bottom border-dark">
<h3>Alkalmazottak</h3>
      <br>

      <%= link_to "Új alkalmazott felvétele", new_office_employee_path(@office), :class => 'btn btn-default' %>
      <br><br>

      <table class="table">
  <thead>
    <tr>
      <th scope="col">Alkalmazott neve</th>
      <th scope="col">Munkakör</th>
      <th scope="col">Fizetés</th>
      <th scope="col">Egyéb adatok</th>
      <th scope="col">Törlés</th>
    </tr>
  </thead>
  <tbody>
<% @office.employees.each do |employee| %>
  <tr>
      <td><%= employee.name %></td>
      <td><%= employee.job %></td>
      <td><%= employee.salary %></td>
      <td><%= link_to "Egyéb adatok, szerkesztés", office_employee_path(employee), :class => 'btn btn-default' %></td>
      <td><%= link_to "Törlés", office_employee_path(employee),
                      method: :delete,
                      data: {confirm: 'Biztosan törlöd?'},
                      :class => 'text-danger' %></td>
    </tr>
<% end %>
</tbody>
</table>

    </span>
  </div>
</div>

app/views/tools/edit.html.erb
<div class="container text-center">
  <br><br>
<h3>Eszköz szerkesztése</h3>
  <br><br>
<%= form_for :tool, url: office_tool_path(@tool), method: :patch do |tool| %>
  <% if @tool.errors.any? %>
      <p class="text-danger">Mindkét mező kitöltése kötelező!</p>
  <% end %>
  <p>
    <%= tool.label :Név %><br>
    <%= tool.text_field(:name, {:class => 'col-sm-4'}) %>
  </p>
  <p>
    <%= tool.label :Mennyiség %><br>
    <%= tool.text_field(:quantity, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= tool.submit("Új adatok elfogadása", {:class => 'btn btn-default'}) %>
  </p>
<% end %>
</div>

app/views/tools/index.html.erb
<h2>Eszközeink listája</h2>
<li><%= link_to "Új eszköz felvétele", new_tool_path %></li>
<% @tools.each do |tool| %>
  <h3><%= tool.name %>, <%= tool.quantity %>, , <%= tool.office_id %></h3>
  <%= link_to "További adatok", edit_tool_path(tool), :class => 'btn btn-default' %>
  <%= link_to "Törlés", tool, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/tools/new.html.erb
<div class="container text-center">
  <br><br>
<h3>Új eszköz felvétele</h3>
  <br><br>
<%= form_for([@office, @office.tools.build]) do |tool| %>
  <% if @tool.errors.any? %>
      <p class="text-danger">Mindkét mező kitöltése kötelező!</p>
  <% end %>
  <p>
    <%= tool.label :Név %><br>
    <%= tool.text_field(:name, {:class => 'col-sm-4'}) %>
  </p>
  <p>
    <%= tool.label :Mennyiség %><br>
    <%= tool.text_field(:quantity, {:class => 'col-sm-4'}) %>
  </p>

  <p>
    <%= tool.submit("Új eszköz létrehozása", {:class => 'btn btn-default'}) %>
  </p>
<% end %>
</div>

app/views/tools/show.html.erb
<div class="container text-center">
  <br><br>
<h2><%= @tool.name %>, <%= @tool.quantity %></h2>
  <br>
<%= link_to "Szerkesztés", edit_office_tool_path(@tool), :class => 'btn btn-default' %>
</div>